# https://docs.cortex.io/docs/reference/basics/entities#service-entities

openapi: 3.0.1
info:
  title: Azure Pipeline Lighthouse
  x-cortex-git:
    github:
      alias: gsoft-inc
      repository: gsoft-inc/azure-pipelines-lighthouse
  x-cortex-tag: service-azure-pipelines-lighthouse
  x-cortex-type: library
  x-cortex-slack:
    channels:
    - name: internal-dev-platform
      notificationsEnabled: true
  x-cortex-owners:
  - name: team-internal-developer-platform-frontend
    type: GROUP
    provider: CORTEX
  x-cortex-link:
  - type: cortex
    url: https://github.com/gsoft-inc/cortex-gitops/blob/main/.cortex/catalog/service-azure-pipelines-lighthouse.yaml
    name: Edit current Cortex entity in GitHub

