name: CI

on:
  pull_request:
    branches: ["main"]
    paths-ignore: ["*.md, **/*.png"]
  
  push:
    branches:
      - "renovate/**"
  
jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install NPM dependencies
        run: npm ci

      - name: Update extension information
        run: npm run updateversion -- --environment dev --version "1.0.0"

      - name: Run tests
        run: npm run test

      - name: Package extension
        run: npm run package
