name: Publish

on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]
    paths-ignore: ["*.md"]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET SDK
        if: ${{ contains(github.ref, 'refs/tags/') }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"

      - name: GitVersion
        if: ${{ contains(github.ref, 'refs/tags/') }}
        run: dotnet tool install --global GitVersion.Tool --version 5.12.0 && dotnet-gitversion /output buildserver

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install NPM dependencies
        run: npm ci

      - name: Update extension information (dev)
        if: ${{ github.ref == 'refs/heads/main' }}
        run: npm run updateversion -- --environment dev --version "1.1.${{ github.run_number }}"

      - name: Update extension information (prod)
        if: ${{ contains(github.ref, 'refs/tags/') }}
        run: npm run updateversion -- --environment prod --version "${{ env.GitVersion_MajorMinorPatch }}"

      - name: Run tests
        run: npm run test

      - name: Package extension
        run: npm run package

      - name: Publish to VS Marketplace (dev)
        if: ${{ github.ref == 'refs/heads/main' }}
        run: find .output/ -name '*.vsix' -exec npm run publish:dev -- -t ${{ secrets.marketplace_access_token }} --vsix {} \;

      - name: Publish to VS Marketplace (prod)
        if: ${{ contains(github.ref, 'refs/tags/') }}
        run: find .output/ -name '*.vsix' -exec npm run publish:prod -- -t ${{ secrets.marketplace_access_token }} --vsix {} \;
